name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: yarn
      - run: yarn test
      - run: yarn build

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: yarn
      - run: yarn semantic-release
        env:
          CI: "true"
          GH_TOKEN: ${{secrets.GH_TOKEN}}

  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: yarn
      - run: yarn build
      - run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$SECRETS_PASSPHRASE" --output secrets/.clasprc.json secrets/clasprc.json.gpg;
          gpg --quiet --batch --yes --decrypt --passphrase="$SECRETS_PASSPHRASE" --output .clasp.json secrets/clasp.json.gpg
        env:
          SECRETS_PASSPHRASE: ${{secrets.SECRETS_PASSPHRASE}}
      - run: npm i -g clasp
      - run: clasp push -f -A ./secrets/.clasprc.json
